#!/usr/bin/env bash
set -e

kodiak_version=$(git rev-parse --short=7 HEAD)
registry=vimc
kodiak_image=${registry}/kodiak:${kodiak_version}

docker run \
    --rm \
    -v kodiak_config:/etc/kodiak/ \
    -v kodiak_logs:/var/log/kodiak \
    ${kodiak_image} "$@"
